name: ssh-tunnel
description: SSH Reverse Tunnel

inputs:
  public_key:
    required: true
    description: Public key to accept for reverse tunnel. Warning, this should not be the public key for the 'private_key' input.
  offer:
    required: true
    description: RTC offer

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install ssh
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
          python3.exe -m pip install requests
          python3.exe installssh.py

    - name: Start SSH
      if: ${{ runner.os == 'Windows' }}
      shell: powershell
      run: |
        Start-Service sshd

    - name: Show sshd configuration
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          cat /etc/ssh/sshd_config
        elif [ "$RUNNER_OS" == "macOS" ]; then
          cat /private/etc/ssh/sshd_config
        else
          cat "C:\ProgramData\ssh\sshd_config"
        fi

    - name: Add ssh public key
      shell: sh
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          mkdir -p /home/runner/.ssh
          chmod 700 /home/runner/.ssh
          touch /home/runner/.ssh/authorized_keys
          echo "${{ inputs.public_key }}" | tee -a /home/runner/.ssh/authorized_keys
        elif [ "$RUNNER_OS" == "macOS" ]; then
          mkdir -p /Users/runner/.ssh
          chmod 700 /Users/runner/.ssh
          touch /Users/runner/.ssh/authorized_keys
          echo "${{ inputs.public_key }}" | tee -a /Users/runner/.ssh/authorized_keys
        else
          echo "${{ inputs.public_key }}" | tee -a "C:\ProgramData\ssh\administrators_authorized_keys"
        fi

    - name: Create rtc tunnel
      shell: bash
      run: |
        python3 -m pip install aiortc
        echo '${{ inputs.offer }}' | python -m rtcforward --port 22 answer
