name: Retry workflow
run-name: Retry workflows

on:
  workflow_dispatch: {}
  schedule:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
    - cron: '*/10 * * * *'

permissions:
  contents: read
  pull-requests: read
  actions: write

jobs:
  rerun:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: rerun ${{ inputs.run_id }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        shell: sh
        run: |
          IFS='' read -r -d '' JQ <<"EOF"
          .[]
           | select(
             ( .updatedAt |fromdate ) > ( $d |tonumber ) and .attempt < 5
           ).databaseId
          EOF
