name: SSH Debug
run-name: "SSH Debug ${{ inputs.runner }}"
on:
  pull_request: {}
  workflow_dispatch:
    inputs:
       runner:
         type: string
         required: True
         description: The runner to start a tunnel on.
       offer:
         type: string
         required: True
         description: SDP Offer
       public_key:
         type: string
         required: True
         description: Your public key for ssh access.



jobs:
  debug:
    runs-on: ${{ inputs.runner }}
    if: ${{ inputs.runner }}
    environment: ci
    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/ssh-tunnel
        with:
          public_key: ${{ inputs.public_key }}
          offer: ${{ inputs.offer }}
